name: Run Selenium Tests

on:
  push:
    branches: ["master"]

jobs:
  selenium-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        java: [11, 19]
        selenium: ['4.24.0']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          cache: maven
          distribution: temurin
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: latest
      - name: Install Selenium Dependencies
        run: |
          mvn clean install -Dselenium.version=${{ matrix.selenium }}
      - name: Run Selenium Tests
        run: mvn clean test