

name: Run Selenium Test

on:
  push:
    branches: ["master"]


jobs:
  tset:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "22.0.2"
          cache: maven
          distribution:  "temurin"

      - uses: browser-actions/setup-chrome@latest
      - run: mvn clean test




