name: Java CI with Maven on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Replace with your JDK version
          distribution: 'temurin'

      - name: Install Chrome
        run: choco install googlechrome

      - name: Install ChromeDriver
        run: choco install chromedriver

      - name: Install Allure
        run: choco install allure

      - name: Build with Maven
        run: mvn clean install test



      # (Optional) Step for generating Allure reports:
      - name: Generate Allure Report
        run: |
          mvn allure:report
          allure serve
