name: Java CI with Maven on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22' # Replace with your JDK version
          distribution: 'temurin'

      - name: Build with Maven (consider adding -DfailFast=true)
        run: mvn clean install test

      # Uncomment and configure if using Allure in pom.xml
      - name: Install Allure (if not using Maven dependency)
        run: choco install allure